version: '3.4'

# https://www.jaegertracing.io/docs/1.22/deployment/
services:
  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    hostname: jaeger
    ports:
      - 6831:6831/udp # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - 6832:6832/udp # accept jaeger.thrift in binary Thrift protocol used by Node.js Jaeger client (because thriftrw npm package does not support compact protocol)
      - 5775:5775/udp # accept zipkin.thrift in compact Thrift protocol (deprecated; only used by very old Jaeger clients, circa 2016)
      - 5778:5778 # serve configs, sampling strategies
      - 16686:16686 # UI port
      - 14269:14269 # collector admin port: health check at / and metrics at /metrics
    environment:
      - MEMORY_MAX_TRACES=100000
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger_data:/badger
    networks:
      - backend_network

  hotrod:
    image: jaegertracing/example-hotrod:1.18
    hostname: hotrod
    ports:
      - 8080:8080 # Navigate to this port to generate traces
      - 8081:8081
      - 8082:8082
      - 8083:8083
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - backend_network

volumes:
  jaeger_data:

networks:
  backend_network: