apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "jaeger-all-in-one.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  host: jaeger-ui-{{ .Release.Namespace }}.apps.private.teh-1.snappcloud.io
  port:
    targetPort: http-ui
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "jaeger-all-in-one.fullname" . }}
    weight: 100
  wildcardPolicy: None
status: 
  ingress: []
